spring:
  application:
    name: itzip
  profiles:
    active: local
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  mongodb:
    embedded:
      version: 4.0.21
school:
  api-url: ${SCHOOL_API_URL}
  api-key: ${SCHOOL_API_KEY}
server:
    servlet:
      context-path: /api