spring:
  application:
    name: itzip
  profiles:
    active: local
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  mongodb:
    embedded:
      version: 4.0.21
  webflux:
    problemdetails:
      enabled: true

school:
  api-url: ${SCHOOL_API_URL}
  api-key: ${SCHOOL_API_KEY}

job:
  api-url: ${JOB_API_URL}
  api-key: ${JOB_API_KEY}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

# 정적 리소스 제공 설정
resources:
  chain:
    strategy:
      content:
        enabled: true
    mime-mappings:
      js: application/javascript

# 기본 Swagger 비활성화 (custom Swagger 사용)
springdoc:
  swagger-ui:
    enabled: false

# API 기본 경로 설정
server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}