drop table if exists hello_entity cascade;
drop table if exists images cascade;
drop table if exists school_infos cascade;
drop table if exists tokens cascade;
drop table if exists users cascade;
drop sequence if exists hello_entity_seq;
drop sequence if exists images_seq;
drop sequence if exists school_seq;

create sequence hello_entity_seq start with 1 increment by 50;
create sequence images_seq start with 1 increment by 50;
create sequence school_seq start with 1 increment by 50;
create table hello_entity (id bigint not null, primary key (id));

create table images (create_date timestamp(6) not null, image_seq bigint not null, image_size bigint, modify_date timestamp(6) not null, image_type varchar(50), image_name varchar(100), image_path varchar(255), primary key (image_seq));

create table school_infos (id bigint not null, school_name varchar(100), address varchar(255), campus_name varchar(255), est_type varchar(255) check (est_type in ('NATIONAL_SCHOOL','PUBLIC_SCHOOL','PRIVATE_SCHOOL')), gubun varchar(255), region varchar(255) check (region in ('SEOUL','BUSAN','INCHEON','DAEJEON','DAEGU','ULSAN','GWANGJI','GYEONGGIDO','GANGWONDO','CHUNGCHEONGBUKDO','CHUNGCHEONGNAMDO','JEONBUK','JEOLLANAMDO','GYEONGSANGBUKDO','GYEONGSANGNAMDO','JEJU','SEJONG')), school_type varchar(255) check (school_type in ('ELEMENTARY_SCHOOL','MIDDLE_SCHOOL','HIGH_SCHOOL','UNIVERSITY','SPECIAL_SCHOOL')), primary key (id));

create table tokens (create_date timestamp(6) not null, id bigint generated by default as identity, modify_date timestamp(6) not null, user_id bigint, access_token varchar(300) not null, refresh_token varchar(300) not null, grant_type varchar(255) not null, primary key (id));
create table users (create_date timestamp(6) not null, id bigint generated by default as identity, modify_date timestamp(6) not null, authority varchar(255) not null check (authority in ('ADMIN','USER')), email varchar(255) not null unique, nickname varchar(255) not null unique, password varchar(255) not null, primary key (id));
